---
language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
    - UI_DIR="ui"
    # Force /dev/urandom for all instances of SecureRandom
    # https://github.com/travis-ci/travis-ci/issues/5235
    - MAVEN_OPTS="-Djava.security.egd=file:/dev/./urandom -Dsecurerandom.strongAlgorithms=NativePRNG"
    - _JAVA_OPTIONS="-Djava.security.egd=file:/dev/./urandom -Dsecurerandom.strongAlgorithms=NativePRNG"

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  # Haveged gives some extra entropy to avoid blocking on RNG
  # https://github.com/travis-ci/travis-ci/issues/5235
  - sudo apt-get install haveged && sudo service haveged start
  # Extra Chrome setup from: http://stackoverflow.com/questions/19255976
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install karma && npm install karma-jasmine karma-chrome-launcher
  - cd $UI_DIR && npm install -g grunt-cli bower
  - npm install
  - bower install
  - grunt build && cd ..

install:
  # Build docker image
  - docker build -t square/keywhiz .

script:
  # Build keywhiz and run tests, reports
  - rm -rf /tmp/h2_data
  - mvn test findbugs:check jacoco:report coveralls:report -q -P h2
  - cd $UI_DIR && grunt test && cd -
